[install]
exact = true
linker = "isolated"
minimumReleaseAge = 259200 # 3 days
minimumReleaseAgeExcludes = ["bun-scan"]

[install.security]
scanner = "bun-scan"

[test]
preload = ["./.test-guard.ts"]
