coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        paths:
          - "packages/zenko/src"
    patch:
<<<<<<< HEAD
      default:
        target: 80%
=======
      off: true
>>>>>>> 07d8e79 (more review fixes)
