openapi: 3.0.1
info:
  title: Mixed Headers
  version: 1.0.0
paths:
  /matrix:
    post:
      operationId: createMatrix
      parameters:
        - $ref: "#/components/parameters/AgentHeader"
        - $ref: "#/components/parameters/TestHeader"
        - $ref: "#/components/parameters/MagicalNumberHeader"
        - $ref: "#/components/parameters/TokenHeader"
      responses:
        "200":
          description: OK
components:
  parameters:
    AgentHeader:
      name: Agent
      in: header
      required: false
      schema:
        type: string
      example: "System"
    TestHeader:
      name: Test
      in: header
      required: true
      schema:
        type: boolean
      example: true
    MagicalNumberHeader:
      name: MagicalNumber
      in: header
      required: false
      schema:
        type: integer
        minimum: 0
        maximum: 100
      example: 42
    TokenHeader:
      name: Token
      in: header
      required: true
      schema:
        type: string
      example: "password"
