openapi: 3.0.1
info:
  title: No Response Content
  version: 1.0.0
paths:
  /data:
    put:
      tags:
        - data
      description: Put something
      operationId: PutSomething
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '503':
          description: Service Unavailable